language: go

go:
  - "1.10"

before_install:
  - eval "$(gimme 1.12)"

services:
  - docker

script:
  - make test
  - make build_image

deploy:
  - provider: script
    script: make upload_image
    on:
      branch: master
