language: go

go:
  - "1.10"

before_install:
  - eval "$(gimme 1.12)"

services:
  - docker

script:
  - make test
  - make build_image
  - make docker_up
  - curl -sL -w "%{http_code}\\n" "http://localhost:24545/health" -o /dev/null --fail --show-error

deploy:
  - provider: script
    script: make upload_image
    on:
      branch: master
