version: "3"

services:
  proxy:
    build: .
    image: tsocial/s3-proxy
    command: ./s3proxy
    ports:
      - 24545:80
    environment:
      - AWS_REGION=ap-southeast-1
      - AWS_ACCESS_KEY_ID=1
      - AWS_SECRET_ACCESS_KEY=1
      - AWS_S3_BUCKET=some-bucket.com
      - AWS_S3_KEY_PREFIX
      - HTTP_CACHE_CONTROL
      - HTTP_EXPIRES
      - BASIC_AUTH_USER
      - BASIC_AUTH_PASS
      - CORS_ALLOW_ORIGIN
      - CORS_ALLOW_METHODS
      - CORS_ALLOW_HEADERS
      - CORS_MAX_AGE
      - ACCESS_LOG=true
      - HEALTHCHECK_PATH=/health
